---
- name: Install tools on localhost Ubuntu instance
  hosts: localhost
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install Python and pip
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install tmux
      apt:
        name: tmux
        state: present

    - name: Install Oh My Tmux
      git:
        repo: 'https://github.com/gpakosz/.tmux.git'
        dest: '~/.tmux'
        version: master
      notify: Enable mouse in tmux

  handlers:
    - name: Enable mouse in tmux
      lineinfile:
        path: ~/.tmux.conf.local
        regexp: '^#?set -g mouse'
        line: 'set -g mouse on'
